
apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: files-persistent-volume-claim 
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: files-persistent-volume